name: network_checker

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:

  flutter:
    sdk: flutter

  connectivity_plus: ^5.0.2

  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0